
application:
    key: JiwhizBlogWeb
    email:
        systemName: Jiwhiz Blog
        systemEmail: system@jiwhizblog.com
        adminName: Jiwhiz Admin
        adminEmail: admin@jiwhizblog.com
        
server:
    port: 8080

spring:
    profiles:
        active: dev,local
    
    data:
        mongodb:
            host: localhost
            database: jiwhizblogweblocaldev
    
    social:
        google:
            appId: 765129884435-oartjuevlu3egh9v1fts49uj0b8go4cm.apps.googleusercontent.com
            appSecret: Fi3z4K1f7lUoqbB0ZCt2L0kd
        facebook: 
            appId: 563627143677454
            appSecret: 823fd02f0c3feb155c51c2f28130b1b4
        twitter:
            appId: lNKlMrMLagrLiGdHj4ptg
            appSecret: LkUVgnqPp22WhQEfBjLqJEYyEOzNS9rJa7LIH4y4
        linkedin:
            appId: 75kyj6lb803vn6
            appSecret: jlJW6XgVZC2RJbGW
            
            